// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAId8BBW1NVWLtUyfK2zxotEpyd3ZmLaU',
    appId: '1:541815583564:web:444c389b10a1ed3dffd5e9',
    messagingSenderId: '541815583564',
    projectId: 'bookflip-001',
    authDomain: 'bookflip-001.firebaseapp.com',
    storageBucket: 'bookflip-001.firebasestorage.app',
    measurementId: 'G-M8RKC0GRRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdLy9lUFFQekNzFdKtYGw6zUJt_-tHvEA',
    appId: '1:541815583564:android:e831e9ba1a3e69fcffd5e9',
    messagingSenderId: '541815583564',
    projectId: 'bookflip-001',
    storageBucket: 'bookflip-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6ClweNBOhc2Wyb5NKUo8Vz8p9bC_3uY',
    appId: '1:541815583564:ios:5c95f24631afce07ffd5e9',
    messagingSenderId: '541815583564',
    projectId: 'bookflip-001',
    storageBucket: 'bookflip-001.firebasestorage.app',
    iosClientId: '541815583564-kldtjdml62fqlgbcmi6vls11hjrl0t76.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookflipMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6ClweNBOhc2Wyb5NKUo8Vz8p9bC_3uY',
    appId: '1:541815583564:ios:5c95f24631afce07ffd5e9',
    messagingSenderId: '541815583564',
    projectId: 'bookflip-001',
    storageBucket: 'bookflip-001.firebasestorage.app',
    iosClientId: '541815583564-kldtjdml62fqlgbcmi6vls11hjrl0t76.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookflipMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAId8BBW1NVWLtUyfK2zxotEpyd3ZmLaU',
    appId: '1:541815583564:web:4745dd8a843d7ca2ffd5e9',
    messagingSenderId: '541815583564',
    projectId: 'bookflip-001',
    authDomain: 'bookflip-001.firebaseapp.com',
    storageBucket: 'bookflip-001.firebasestorage.app',
    measurementId: 'G-854EQBJWKC',
  );
}
